// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticalThirteen.Data.Contexts;

#nullable disable

namespace PracticalThirteen.Data.Migrations
{
    [DbContext(typeof(EmployeeCodeFirstDBContext))]
    [Migration("20230704223149_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PracticalThirteen.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            JoiningDate = new DateTime(2002, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bhavin"
                        },
                        new
                        {
                            Id = 2,
                            Age = 23,
                            JoiningDate = new DateTime(1999, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Vipul"
                        },
                        new
                        {
                            Id = 3,
                            Age = 22,
                            JoiningDate = new DateTime(2000, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jil"
                        },
                        new
                        {
                            Id = 4,
                            Age = 22,
                            JoiningDate = new DateTime(2000, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Abhi"
                        },
                        new
                        {
                            Id = 5,
                            Age = 22,
                            JoiningDate = new DateTime(2000, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jay"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
